/**
 * @project Engraced Smiles
 * @author Daniel Innocent <@mdtbmw>
 * @copyright Copyright (c) 2024. All rights reserved.
 * This software is the exclusive property of Daniel Innocent.
 * A license has been granted to Mr. Ismail Muhammed for resale to Engraced Smiles.
 */

export type Country = {
  name: string
  flag: string
  iso2: string
  iso3: string
}

export const countries: Country[] = [
  {
    name: 'Nigeria',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NG.svg',
    iso2: 'NG',
    iso3: 'NGA',
  },
  {
    name: 'Afghanistan',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AF.svg',
    iso2: 'AF',
    iso3: 'AFG',
  },
  {
    name: 'Albania',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AL.svg',
    iso2: 'AL',
    iso3: 'ALB',
  },
  {
    name: 'Algeria',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DZ.svg',
    iso2: 'DZ',
    iso3: 'DZA',
  },
  {
    name: 'American Samoa',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AS.svg',
    iso2: 'AS',
    iso3: 'ASM',
  },
  {
    name: 'Andorra',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AD.svg',
    iso2: 'AD',
    iso3: 'AND',
  },
  {
    name: 'Angola',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AO.svg',
    iso2: 'AO',
    iso3: 'AGO',
  },
  {
    name: 'Anguilla',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AI.svg',
    iso2: 'AI',
    iso3: 'AIA',
  },
  {
    name: 'Antigua and Barbuda',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AG.svg',
    iso2: 'AG',
    iso3: 'ATG',
  },
  {
    name: 'Argentina',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AR.svg',
    iso2: 'AR',
    iso3: 'ARG',
  },
  {
    name: 'Armenia',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AM.svg',
    iso2: 'AM',
    iso3: 'ARM',
  },
  {
    name: 'Aruba',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AW.svg',
    iso2: 'AW',
    iso3: 'ABW',
  },
  {
    name: 'Australia',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AU.svg',
    iso2: 'AU',
    iso3: 'AUS',
  },
  {
    name: 'Austria',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AT.svg',
    iso2: 'AT',
    iso3: 'AUT',
  },
  {
    name: 'Azerbaijan',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AZ.svg',
    iso2: 'AZ',
    iso3: 'AZE',
  },
  {
    name: 'Bahamas',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BS.svg',
    iso2: 'BS',
    iso3: 'BHS',
  },
  {
    name: 'Bahrain',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BH.svg',
    iso2: 'BH',
    iso3: 'BHR',
  },
  {
    name: 'Bangladesh',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BD.svg',
    iso2: 'BD',
    iso3: 'BGD',
  },
  {
    name: 'Barbados',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BB.svg',
    iso2: 'BB',
    iso3: 'BRB',
  },
  {
    name: 'Belarus',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BY.svg',
    iso2: 'BY',
    iso3: 'BLR',
  },
  {
    name: 'Belgium',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BE.svg',
    iso2: 'BE',
    iso3: 'BEL',
  },
  {
    name: 'Belize',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BZ.svg',
    iso2: 'BZ',
    iso3: 'BLZ',
  },
  {
    name: 'Benin',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BJ.svg',
    iso2: 'BJ',
    iso3: 'BEN',
  },
  {
    name: 'Bermuda',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BM.svg',
    iso2: 'BM',
    iso3: 'BMU',
  },
  {
    name: 'Bhutan',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BT.svg',
    iso2: 'BT',
    iso3: 'BTN',
  },
  {
    name: 'Bolivia',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BO.svg',
    iso2: 'BO',
    iso3: 'BOL',
  },
  {
    name: 'Bosnia and Herzegovina',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BA.svg',
    iso2: 'BA',
    iso3: 'BIH',
  },
  {
    name: 'Botswana',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BW.svg',
    iso2: 'BW',
    iso3: 'BWA',
  },
  {
    name: 'Brazil',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BR.svg',
    iso2: 'BR',
    iso3: 'BRA',
  },
  {
    name: 'British Indian Ocean Territory',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IO.svg',
    iso2: 'IO',
    iso3: 'IOT',
  },
  {
    name: 'British Virgin Islands',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VG.svg',
    iso2: 'VG',
    iso3: 'VGB',
  },
  {
    name: 'Brunei',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BN.svg',
    iso2: 'BN',
    iso3: 'BRN',
  },
  {
    name: 'Bulgaria',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BG.svg',
    iso2: 'BG',
    iso3: 'BGR',
  },
  {
    name: 'Burkina Faso',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BF.svg',
    iso2: 'BF',
    iso3: 'BFA',
  },
  {
    name: 'Burundi',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BI.svg',
    iso2: 'BI',
    iso3: 'BDI',
  },
  {
    name: 'Cambodia',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KH.svg',
    iso2: 'KH',
    iso3: 'KHM',
  },
  {
    name: 'Cameroon',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CM.svg',
    iso2: 'CM',
    iso3: 'CMR',
  },
  {
    name: 'Canada',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CA.svg',
    iso2: 'CA',
    iso3: 'CAN',
  },
  {
    name: 'Cape Verde',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CV.svg',
    iso2: 'CV',
    iso3: 'CPV',
  },
  {
    name: 'Cayman Islands',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KY.svg',
    iso2: 'KY',
    iso3: 'CYM',
  },
  {
    name: 'Central African Republic',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CF.svg',
    iso2: 'CF',
    iso3: 'CAF',
  },
  {
    name: 'Chad',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TD.svg',
    iso2: 'TD',
    iso3: 'TCD',
  },
  {
    name: 'Chile',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CL.svg',
    iso2: 'CL',
    iso3: 'CHL',
  },
  {
    name: 'China',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CN.svg',
    iso2: 'CN',
    iso3: 'CHN',
  },
  {
    name: 'Christmas Island',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CX.svg',
    iso2: 'CX',
    iso3: 'CXR',
  },
  {
    name: 'Cocos (Keeling) Islands',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CC.svg',
    iso2: 'CC',
    iso3: 'CCK',
  },
  {
    name: 'Colombia',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CO.svg',
    iso2: 'CO',
    iso3: 'COL',
  },
  {
    name: 'Comoros',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KM.svg',
    iso2: 'KM',
    iso3: 'COM',
  },
  {
    name: 'Cook Islands',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CK.svg',
    iso2: 'CK',
    iso3: 'COK',
  },
  {
    name: 'Costa Rica',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CR.svg',
    iso2: 'CR',
    iso3: 'CRI',
  },
  {
    name: 'Croatia',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HR.svg',
    iso2: 'HR',
    iso3: 'HRV',
  },
  {
    name: 'Cuba',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CU.svg',
    iso2: 'CU',
    iso3: 'CUB',
  },
  {
    name: 'Curacao',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CW.svg',
    iso2: 'CW',
    iso3: 'CUW',
  },
  {
    name: 'Cyprus',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CY.svg',
    iso2: 'CY',
    iso3: 'CYP',
  },
  {
    name: 'Czech Republic',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CZ.svg',
    iso2: 'CZ',
    iso3: 'CZE',
  },
  {
    name: 'Democratic Republic of the Congo',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CD.svg',
    iso2: 'CD',
    iso3: 'COD',
  },
  {
    name: 'Denmark',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DK.svg',
    iso2: 'DK',
    iso3: 'DNK',
  },
  {
    name: 'Djibouti',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DJ.svg',
    iso2: 'DJ',
    iso3: 'DJI',
  },
  {
    name: 'Dominica',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DM.svg',
    iso2: 'DM',
    iso3: 'DMA',
  },
  {
    name: 'Dominican Republic',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DO.svg',
    iso2: 'DO',
    iso3: 'DOM',
  },
  {
    name: 'Ecuador',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EC.svg',
    iso2: 'EC',
    iso3: 'ECU',
  },
  {
    name: 'Egypt',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EG.svg',
    iso2: 'EG',
    iso3: 'EGY',
  },
  {
    name: 'El Salvador',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SV.svg',
    iso2: 'SV',
    iso3: 'SLV',
  },
  {
    name: 'Equatorial Guinea',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GQ.svg',
    iso2: 'GQ',
    iso3: 'GNQ',
  },
  {
    name: 'Eritrea',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ER.svg',
    iso2: 'ER',
    iso3: 'ERI',
  },
  {
    name: 'Estonia',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EE.svg',
    iso2: 'EE',
    iso3: 'EST',
  },
  {
    name: 'Eswatini',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SZ.svg',
    iso2: 'SZ',
    iso3: 'SWZ',
  },
  {
    name: 'Ethiopia',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ET.svg',
    iso2: 'ET',
    iso3: 'ETH',
  },
  {
    name: 'Falkland Islands',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FK.svg',
    iso2: 'FK',
    iso3: 'FLK',
  },
  {
    name: 'Faroe Islands',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FO.svg',
    iso2: 'FO',
    iso3: 'FRO',
  },
  {
    name: 'Fiji',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FJ.svg',
    iso2: 'FJ',
    iso3: 'FJI',
  },
  {
    name: 'Finland',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FI.svg',
    iso2: 'FI',
    iso3: 'FIN',
  },
  {
    name: 'France',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FR.svg',
    iso2: 'FR',
    iso3: 'FRA',
  },
  {
    name: 'French Guiana',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GF.svg',
    iso2: 'GF',
    iso3: 'GUF',
  },
  {
    name: 'French Polynesia',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PF.svg',
    iso2: 'PF',
    iso3: 'PYF',
  },
  {
    name: 'Gabon',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GA.svg',
    iso2: 'GA',
    iso3: 'GAB',
  },
  {
    name: 'Gambia',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GM.svg',
    iso2: 'GM',
    iso3: 'GMB',
  },
  {
    name: 'Georgia',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GE.svg',
    iso2: 'GE',
    iso3: 'GEO',
  },
  {
    name: 'Germany',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DE.svg',
    iso2: 'DE',
    iso3: 'DEU',
  },
  {
    name: 'Ghana',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GH.svg',
    iso2: 'GH',
    iso3: 'GHA',
  },
  {
    name: 'Gibraltar',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GI.svg',
    iso2: 'GI',
    iso3: 'GIB',
  },
  {
    name: 'Greece',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GR.svg',
    iso2: 'GR',
    iso3: 'GRC',
  },
  {
    name: 'Greenland',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GL.svg',
    iso2: 'GL',
    iso3: 'GRL',
  },
  {
    name: 'Grenada',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GD.svg',
    iso2: 'GD',
    iso3: 'GRD',
  },
  {
    name: 'Guadeloupe',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GP.svg',
    iso2: 'GP',
    iso3: 'GLP',
  },
  {
    name: 'Guam',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GU.svg',
    iso2: 'GU',
    iso3: 'GUM',
  },
  {
    name: 'Guatemala',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GT.svg',
    iso2: 'GT',
    iso3: 'GTM',
  },
  {
    name: 'Guernsey',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GG.svg',
    iso2: 'GG',
    iso3: 'GGY',
  },
  {
    name: 'Guinea',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GN.svg',
    iso2: 'GN',
    iso3: 'GIN',
  },
  {
    name: 'Guinea-Bissau',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GW.svg',
    iso2: 'GW',
    iso3: 'GNB',
  },
  {
    name: 'Guyana',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GY.svg',
    iso2: 'GY',
    iso3: 'GUY',
  },
  {
    name: 'Haiti',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HT.svg',
    iso2: 'HT',
    iso3: 'HTI',
  },
  {
    name: 'Honduras',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HN.svg',
    iso2: 'HN',
    iso3: 'HND',
  },
  {
    name: 'Hong Kong',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HK.svg',
    iso2: 'HK',
    iso3: 'HKG',
  },
  {
    name: 'Hungary',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HU.svg',
    iso2: 'HU',
    iso3: 'HUN',
  },
  {
    name: 'Iceland',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IS.svg',
    iso2: 'IS',
    iso3: 'ISL',
  },
  {
    name: 'India',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IN.svg',
    iso2: 'IN',
    iso3: 'IND',
  },
  {
    name: 'Indonesia',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ID.svg',
    iso2: 'ID',
    iso3: 'IDN',
  },
  {
    name: 'Iran',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IR.svg',
    iso2: 'IR',
    iso3: 'IRN',
  },
  {
    name: 'Iraq',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IQ.svg',
    iso2: 'IQ',
    iso3: 'IRQ',
  },
  {
    name: 'Ireland',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IE.svg',
    iso2: 'IE',
    iso3: 'IRL',
  },
  {
    name: 'Isle of Man',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IM.svg',
    iso2: 'IM',
    iso3: 'IMN',
  },
  {
    name: 'Israel',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IL.svg',
    iso2: 'IL',
    iso3: 'ISR',
  },
  {
    name: 'Italy',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IT.svg',
    iso2: 'IT',
    iso3: 'ITA',
  },
  {
    name: 'Ivory Coast',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CI.svg',
    iso2: 'CI',
    iso3: 'CIV',
  },
  {
    name: 'Jamaica',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JM.svg',
    iso2: 'JM',
    iso3: 'JAM',
  },
  {
    name: 'Japan',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JP.svg',
    iso2: 'JP',
    iso3: 'JPN',
  },
  {
    name: 'Jersey',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JE.svg',
    iso2: 'JE',
    iso3: 'JEY',
  },
  {
    name: 'Jordan',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JO.svg',
    iso2: 'JO',
    iso3: 'JOR',
  },
  {
    name: 'Kazakhstan',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KZ.svg',
    iso2: 'KZ',
    iso3: 'KAZ',
  },
  {
    name: 'Kenya',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KE.svg',
    iso2: 'KE',
    iso3: 'KEN',
  },
  {
    name: 'Kiribati',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KI.svg',
    iso2: 'KI',
    iso3: 'KIR',
  },
  {
    name: 'Kosovo',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/XK.svg',
    iso2: 'XK',
    iso3: 'XKX',
  },
  {
    name: 'Kuwait',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KW.svg',
    iso2: 'KW',
    iso3: 'KWT',
  },
  {
    name: 'Kyrgyzstan',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KG.svg',
    iso2: 'KG',
    iso3: 'KGZ',
  },
  {
    name: 'Laos',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LA.svg',
    iso2: 'LA',
    iso3: 'LAO',
  },
  {
    name: 'Latvia',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LV.svg',
    iso2: 'LV',
    iso3: 'LVA',
  },
  {
    name: 'Lebanon',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LB.svg',
    iso2: 'LB',
    iso3: 'LBN',
  },
  {
    name: 'Lesotho',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LS.svg',
    iso2: 'LS',
    iso3: 'LSO',
  },
  {
    name: 'Liberia',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LR.svg',
    iso2: 'LR',
    iso3: 'LBR',
  },
  {
    name: 'Libya',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LY.svg',
    iso2: 'LY',
    iso3: 'LBY',
  },
  {
    name: 'Liechtenstein',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LI.svg',
    iso2: 'LI',
    iso3: 'LIE',
  },
  {
    name: 'Lithuania',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LT.svg',
    iso2: 'LT',
    iso3: 'LTU',
  },
  {
    name: 'Luxembourg',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LU.svg',
    iso2: 'LU',
    iso3: 'LUX',
  },
  {
    name: 'Macau',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MO.svg',
    iso2: 'MO',
    iso3: 'MAC',
  },
  {
    name: 'Madagascar',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MG.svg',
    iso2: 'MG',
    iso3: 'MDG',
  },
  {
    name: 'Malawi',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MW.svg',
    iso2: 'MW',
    iso3: 'MWI',
  },
  {
    name: 'Malaysia',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MY.svg',
    iso2: 'MY',
    iso3: 'MYS',
  },
  {
    name: 'Maldives',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MV.svg',
    iso2: 'MV',
    iso3: 'MDV',
  },
  {
    name: 'Mali',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ML.svg',
    iso2: 'ML',
    iso3: 'MLI',
  },
  {
    name: 'Malta',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MT.svg',
    iso2: 'MT',
    iso3: 'MLT',
  },
  {
    name: 'Marshall Islands',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MH.svg',
    iso2: 'MH',
    iso3: 'MHL',
  },
  {
    name: 'Martinique',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MQ.svg',
    iso2: 'MQ',
    iso3: 'MTQ',
  },
  {
    name: 'Mauritania',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MR.svg',
    iso2: 'MR',
    iso3: 'MRT',
  },
  {
    name: 'Mauritius',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MU.svg',
    iso2: 'MU',
    iso3: 'MUS',
  },
  {
    name: 'Mayotte',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/YT.svg',
    iso2: 'YT',
    iso3: 'MYT',
  },
  {
    name: 'Mexico',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MX.svg',
    iso2: 'MX',
    iso3: 'MEX',
  },
  {
    name: 'Micronesia',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FM.svg',
    iso2: 'FM',
    iso3: 'FSM',
  },
  {
    name: 'Moldova',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MD.svg',
    iso2: 'MD',
    iso3: 'MDA',
  },
  {
    name: 'Monaco',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MC.svg',
    iso2: 'MC',
    iso3: 'MCO',
  },
  {
    name: 'Mongolia',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MN.svg',
    iso2: 'MN',
    iso3: 'MNG',
  },
  {
    name: 'Montenegro',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ME.svg',
    iso2: 'ME',
    iso3: 'MNE',
  },
  {
    name: 'Montserrat',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MS.svg',
    iso2: 'MS',
    iso3: 'MSR',
  },
  {
    name: 'Morocco',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MA.svg',
    iso2: 'MA',
    iso3: 'MAR',
  },
  {
    name: 'Mozambique',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MZ.svg',
    iso2: 'MZ',
    iso3: 'MOZ',
  },
  {
    name: 'Myanmar',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MM.svg',
    iso2: 'MM',
    iso3: 'MMR',
  },
  {
    name: 'Namibia',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NA.svg',
    iso2: 'NA',
    iso3: 'NAM',
  },
  {
    name: 'Nauru',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NR.svg',
    iso2: 'NR',
    iso3: 'NRU',
  },
  {
    name: 'Nepal',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NP.svg',
    iso2: 'NP',
    iso3: 'NPL',
  },
  {
    name: 'Netherlands',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NL.svg',
    iso2: 'NL',
    iso3: 'NLD',
  },
  {
    name: 'New Caledonia',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NC.svg',
    iso2: 'NC',
    iso3: 'NCL',
  },
  {
    name: 'New Zealand',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NZ.svg',
    iso2: 'NZ',
    iso3: 'NZL',
  },
  {
    name: 'Nicaragua',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NI.svg',
    iso2: 'NI',
    iso3: 'NIC',
  },
  {
    name: 'Niger',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NE.svg',
    iso2: 'NE',
    iso3: 'NER',
  },
  {
    name: 'Niue',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NU.svg',
    iso2: 'NU',
    iso3: 'NIU',
  },
  {
    name: 'Norfolk Island',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NF.svg',
    iso2: 'NF',
    iso3: 'NFK',
  },
  {
    name: 'North Korea',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KP.svg',
    iso2: 'KP',
    iso3: 'PRK',
  },
  {
    name: 'North Macedonia',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MK.svg',
    iso2: 'MK',
    iso3: 'MKD',
  },
  {
    name: 'Northern Mariana Islands',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MP.svg',
    iso2: 'MP',
    iso3: 'MNP',
  },
  {
    name: 'Norway',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NO.svg',
    iso2: 'NO',
    iso3: 'NOR',
  },
  {
    name: 'Oman',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/OM.svg',
    iso2: 'OM',
    iso3: 'OMN',
  },
  {
    name: 'Pakistan',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PK.svg',
    iso2: 'PK',
    iso3: 'PAK',
  },
  {
    name: 'Palau',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PW.svg',
    iso2: 'PW',
    iso3: 'PLW',
  },
  {
    name: 'Palestine',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PS.svg',
    iso2: 'PS',
    iso3: 'PSE',
  },
  {
    name: 'Panama',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PA.svg',
    iso2: 'PA',
    iso3: 'PAN',
  },
  {
    name: 'Papua New Guinea',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PG.svg',
    iso2: 'PG',
    iso3: 'PNG',
  },
  {
    name: 'Paraguay',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PY.svg',
    iso2: 'PY',
    iso3: 'PRY',
  },
  {
    name: 'Peru',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PE.svg',
    iso2: 'PE',
    iso3: 'PER',
  },
  {
    name: 'Philippines',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PH.svg',
    iso2: 'PH',
    iso3: 'PHL',
  },
  {
    name: 'Poland',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PL.svg',
    iso2: 'PL',
    iso3: 'POL',
  },
  {
    name: 'Portugal',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PT.svg',
    iso2: 'PT',
    iso3: 'PRT',
  },
  {
    name: 'Puerto Rico',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PR.svg',
    iso2: 'PR',
    iso3: 'PRI',
  },
  {
    name: 'Qatar',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/QA.svg',
    iso2: 'QA',
    iso3: 'QAT',
  },
  {
    name: 'Republic of the Congo',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CG.svg',
    iso2: 'CG',
    iso3: 'COG',
  },
  {
    name: 'Reunion',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RE.svg',
    iso2: 'RE',
    iso3: 'REU',
  },
  {
    name: 'Romania',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RO.svg',
    iso2: 'RO',
    iso3: 'ROU',
  },
  {
    name: 'Russia',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RU.svg',
    iso2: 'RU',
    iso3: 'RUS',
  },
  {
    name: 'Rwanda',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RW.svg',
    iso2: 'RW',
    iso3: 'RWA',
  },
  {
    name: 'Saint Barthelemy',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BL.svg',
    iso2: 'BL',
    iso3: 'BLM',
  },
  {
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SH.svg',
    iso2: 'SH',
    iso3: 'SHN',
  },
  {
    name: 'Saint Kitts and Nevis',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KN.svg',
    iso2: 'KN',
    iso3: 'KNA',
  },
  {
    name: 'Saint Lucia',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LC.svg',
    iso2: 'LC',
    iso3: 'LCA',
  },
  {
    name: 'Saint Martin',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MF.svg',
    iso2: 'MF',
    iso3: 'MAF',
  },
  {
    name: 'Saint Pierre and Miquelon',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PM.svg',
    iso2: 'PM',
    iso3: 'SPM',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VC.svg',
    iso2: 'VC',
    iso3: 'VCT',
  },
  {
    name: 'Samoa',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/WS.svg',
    iso2: 'WS',
    iso3: 'WSM',
  },
  {
    name: 'San Marino',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SM.svg',
    iso2: 'SM',
    iso3: 'SMR',
  },
  {
    name: 'Sao Tome and Principe',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ST.svg',
    iso2: 'ST',
    iso3: 'STP',
  },
  {
    name: 'Saudi Arabia',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SA.svg',
    iso2: 'SA',
    iso3: 'SAU',
  },
  {
    name: 'Senegal',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SN.svg',
    iso2: 'SN',
    iso3: 'SEN',
  },
  {
    name: 'Serbia',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RS.svg',
    iso2: 'RS',
    iso3: 'SRB',
  },
  {
    name: 'Seychelles',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SC.svg',
    iso2: 'SC',
    iso3: 'SYC',
  },
  {
    name: 'Sierra Leone',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SL.svg',
    iso2: 'SL',
    iso3: 'SLE',
  },
  {
    name: 'Singapore',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SG.svg',
    iso2: 'SG',
    iso3: 'SGP',
  },
  {
    name: 'Sint Maarten',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SX.svg',
    iso2: 'SX',
    iso3: 'SXM',
  },
  {
    name: 'Slovakia',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SK.svg',
    iso2: 'SK',
    iso3: 'SVK',
  },
  {
    name: 'Slovenia',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SI.svg',
    iso2: 'SI',
    iso3: 'SVN',
  },
  {
    name: 'Solomon Islands',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SB.svg',
    iso2: 'SB',
    iso3: 'SLB',
  },
  {
    name: 'Somalia',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SO.svg',
    iso2: 'SO',
    iso3: 'SOM',
  },
  {
    name: 'South Africa',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZA.svg',
    iso2: 'ZA',
    iso3: 'ZAF',
  },
  {
    name: 'South Korea',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KR.svg',
    iso2: 'KR',
    iso3: 'KOR',
  },
  {
    name: 'South Sudan',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SS.svg',
    iso2: 'SS',
    iso3: 'SSD',
  },
  {
    name: 'Spain',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ES.svg',
    iso2: 'ES',
    iso3: 'ESP',
  },
  {
    name: 'Sri Lanka',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LK.svg',
    iso2: 'LK',
    iso3: 'LKA',
  },
  {
    name: 'Sudan',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SD.svg',
    iso2: 'SD',
    iso3: 'SDN',
  },
  {
    name: 'Suriname',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SR.svg',
    iso2: 'SR',
    iso3: 'SUR',
  },
  {
    name: 'Svalbard and Jan Mayen',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SJ.svg',
    iso2: 'SJ',
    iso3: 'SJM',
  },
  {
    name: 'Sweden',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SE.svg',
    iso2: 'SE',
    iso3: 'SWE',
  },
  {
    name: 'Switzerland',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CH.svg',
    iso2: 'CH',
    iso3: 'CHE',
  },
  {
    name: 'Syria',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SY.svg',
    iso2: 'SY',
    iso3: 'SYR',
  },
  {
    name: 'Taiwan',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TW.svg',
    iso2: 'TW',
    iso3: 'TWN',
  },
  {
    name: 'Tajikistan',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TJ.svg',
    iso2: 'TJ',
    iso3: 'TJK',
  },
  {
    name: 'Tanzania',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TZ.svg',
    iso2: 'TZ',
    iso3: 'TZA',
  },
  {
    name: 'Thailand',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TH.svg',
    iso2: 'TH',
    iso3: 'THA',
  },
  {
    name: 'Timor-Leste',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TL.svg',
    iso2: 'TL',
    iso3: 'TLS',
  },
  {
    name: 'Togo',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TG.svg',
    iso2: 'TG',
    iso3: 'TGO',
  },
  {
    name: 'Tokelau',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TK.svg',
    iso2: 'TK',
    iso3: 'TKL',
  },
  {
    name: 'Tonga',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TO.svg',
    iso2: 'TO',
    iso3: 'TON',
  },
  {
    name: 'Trinidad and Tobago',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TT.svg',
    iso2: 'TT',
    iso3: 'TTO',
  },
  {
    name: 'Tunisia',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TN.svg',
    iso2: 'TN',
    iso3: 'TUN',
  },
  {
    name: 'Turkey',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TR.svg',
    iso2: 'TR',
    iso3: 'TUR',
  },
  {
    name: 'Turkmenistan',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TM.svg',
    iso2: 'TM',
    iso3: 'TKM',
  },
  {
    name: 'Turks and Caicos Islands',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TC.svg',
    iso2: 'TC',
    iso3: 'TCA',
  },
  {
    name: 'Tuvalu',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TV.svg',
    iso2: 'TV',
    iso3: 'TUV',
  },
  {
    name: 'U.S. Virgin Islands',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VI.svg',
    iso2: 'VI',
    iso3: 'VIR',
  },
  {
    name: 'Uganda',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UG.svg',
    iso2: 'UG',
    iso3: 'UGA',
  },
  {
    name: 'Ukraine',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UA.svg',
    iso2: 'UA',
    iso3: 'UKR',
  },
  {
    name: 'United Arab Emirates',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AE.svg',
    iso2: 'AE',
    iso3: 'ARE',
  },
  {
    name: 'United Kingdom',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GB.svg',
    iso2: 'GB',
    iso3: 'GBR',
  },
  {
    name: 'United States',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/US.svg',
    iso2: 'US',
    iso3: 'USA',
  },
  {
    name: 'Uruguay',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UY.svg',
    iso2: 'UY',
    iso3: 'URY',
  },
  {
    name: 'Uzbekistan',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UZ.svg',
    iso2: 'UZ',
    iso3: 'UZB',
  },
  {
    name: 'Vanuatu',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VU.svg',
    iso2: 'VU',
    iso3: 'VUT',
  },
  {
    name: 'Vatican City',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VA.svg',
    iso2: 'VA',
    iso3: 'VAT',
  },
  {
    name: 'Venezuela',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VE.svg',
    iso2: 'VE',
    iso3: 'VEN',
  },
  {
    name: 'Vietnam',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VN.svg',
    iso2: 'VN',
    iso3: 'VNM',
  },
  {
    name: 'Wallis and Futuna',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/WF.svg',
    iso2: 'WF',
    iso3: 'WLF',
  },
  {
    name: 'Western Sahara',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EH.svg',
    iso2: 'EH',
    iso3: 'ESH',
  },
  {
    name: 'Yemen',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/YE.svg',
    iso2: 'YE',
    iso3: 'YEM',
  },
  {
    name: 'Zambia',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZM.svg',
    iso2: 'ZM',
    iso3: 'ZMB',
  },
  {
    name: 'Zimbabwe',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZW.svg',
    iso2: 'ZW',
    iso3: 'ZWE',
  },
  {
    name: 'Aland Islands',
    flag: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AX.svg',
    iso2: 'AX',
    iso3: 'ALA',
  },
]
/**
 * This file is part of the Engraced Smiles project.
 * Unauthorized reproduction or distribution of this file, or any portion of it,
 * may result in severe civil and criminal penalties, and will be prosecuted
 * to the maximum extent possible under the law.
 *
 * @see https://github.com/mdtbmw
 */
