version: '3.8'

services:
  static-site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: engracedsmile-pwa-site
    restart: unless-stopped
    ports:
      - "8085:80"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

